In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("E0.csv")

In [3]:
data

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,13/08/2021,20:00,Brentford,Arsenal,2,0,H,1,0,...,1.62,0.50,1.75,2.05,1.81,2.13,2.05,2.17,1.80,2.09
1,E0,14/08/2021,12:30,Man United,Leeds,5,1,H,1,0,...,2.25,-1.00,2.05,1.75,2.17,1.77,2.19,1.93,2.10,1.79
2,E0,14/08/2021,15:00,Burnley,Brighton,1,2,A,1,0,...,1.62,0.25,1.79,2.15,1.81,2.14,1.82,2.19,1.79,2.12
3,E0,14/08/2021,15:00,Chelsea,Crystal Palace,3,0,H,2,0,...,1.94,-1.50,2.05,1.75,2.12,1.81,2.16,1.93,2.06,1.82
4,E0,14/08/2021,15:00,Everton,Southampton,3,1,H,0,1,...,1.67,-0.50,2.05,1.88,2.05,1.88,2.08,1.90,2.03,1.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
251,E0,26/02/2022,15:00,Crystal Palace,Burnley,1,1,D,1,0,...,1.62,-0.50,1.90,2.00,1.92,2.01,1.95,2.06,1.91,1.97
252,E0,26/02/2022,15:00,Man United,Watford,0,0,D,0,0,...,2.15,-1.25,1.87,2.03,1.88,2.05,1.91,2.19,1.86,2.03
253,E0,26/02/2022,15:30,Brighton,Aston Villa,0,2,A,0,1,...,1.70,-0.25,1.91,1.99,1.93,2.00,1.96,2.02,1.90,1.97
254,E0,26/02/2022,17:30,Everton,Man City,0,1,A,0,0,...,2.50,1.75,1.92,1.98,2.01,1.89,2.05,1.99,1.95,1.92
255,E0,27/02/2022,14:00,West Ham,Wolves,1,0,H,0,0,...,1.63,-0.50,1.94,1.96,1.94,1.98,1.97,2.00,1.94,1.94

In [4]:
# http://football-data.co.uk/notes.txt

In [5]:
column_list = list(data.columns)

In [6]:
column_list

['Div',
 'Date',
 'Time',
 'HomeTeam',
 'AwayTeam',
 'FTHG',
 'FTAG',
 'FTR',
 'HTHG',
 'HTAG',
 'HTR',
 'Referee',
 'HS',
 'AS',
 'HST',
 'AST',
 'HF',
 'AF',
 'HC',
 'AC',
 'HY',
 'AY',
 'HR',
 'AR',
 'B365H',
 'B365D',
 'B365A',
 'BWH',
 'BWD',
 'BWA',
 'IWH',
 'IWD',
 'IWA',
 'PSH',
 'PSD',
 'PSA',
 'WHH',
 'WHD',
 'WHA',
 'VCH',
 'VCD',
 'VCA',
 'MaxH',
 'MaxD',
 'MaxA',
 'AvgH',
 'AvgD',
 'AvgA',
 'B365>2.5',
 'B365<2.5',
 'P>2.5',
 'P<2.5',
 'Max>2.5',
 'Max<2.5',
 'Avg>2.5',
 'Avg<2.5',
 'AHh',
 'B365AHH',
 'B365AHA',
 'PAHH',
 'PAHA',
 'MaxAHH',
 'MaxAHA',
 'AvgAHH',
 'AvgAHA',
 'B365CH',
 'B365CD',
 'B365CA',
 'BWCH',
 'BWCD',
 'BWCA',
 'IWCH',
 'IWCD',
 'IWCA',
 'PSCH',
 'PSCD',
 'PSCA',
 'WHCH',
 'WHCD',
 'WHCA',
 'VCCH',
 'VCCD',
 'VCCA',
 'MaxCH',
 'MaxCD',
 'MaxCA',
 'AvgCH',
 'AvgCD',
 'AvgCA',
 'B365C>2.5',
 'B365C<2.5',
 'PC>2.5',
 'PC<2.5',
 'MaxC>2.5',
 'MaxC<2.5',
 'AvgC>2.5',
 'AvgC<2.5',
 'AHCh',
 'B365CAHH',
 'B365CAHA',
 'PCAHH',
 'PCAHA',
 'MaxCAHH',
 'MaxCAHA',
 'AvgCAHH',
 'AvgCAHA']

In [7]:
newlist_columns = ['Date', 'Time', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG', 'HTAG', 'HTR', 'Referee',
                  'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC', 'HY', 'AY', 'HR', 'AR', 'MaxH', 'MaxD', 'MaxA',
                  'Max>2.5','Max<2.5',  ]

In [8]:
removed_list = data.drop(newlist_columns, axis=1)
removed_list

,Div,B365H,B365D,B365A,BWH,BWD,BWA,IWH,IWD,IWA,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,4.00,3.40,1.95,4.00,3.50,1.95,3.80,3.40,2.05,...,1.62,0.50,1.75,2.05,1.81,2.13,2.05,2.17,1.80,2.09
1,E0,1.53,4.50,5.75,1.53,4.50,5.75,1.55,4.40,5.75,...,2.25,-1.00,2.05,1.75,2.17,1.77,2.19,1.93,2.10,1.79
2,E0,3.10,3.10,2.45,3.20,3.10,2.40,3.15,3.05,2.45,...,1.62,0.25,1.79,2.15,1.81,2.14,1.82,2.19,1.79,2.12
3,E0,1.25,5.75,13.00,1.28,5.75,10.50,1.25,6.00,13.00,...,1.94,-1.50,2.05,1.75,2.12,1.81,2.16,1.93,2.06,1.82
4,E0,1.90,3.50,4.00,1.95,3.50,3.90,1.95,3.45,3.95,...,1.67,-0.50,2.05,1.88,2.05,1.88,2.08,1.90,2.03,1.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
251,E0,1.90,3.60,4.00,1.90,3.40,4.20,1.95,3.40,4.10,...,1.62,-0.50,1.90,2.00,1.92,2.01,1.95,2.06,1.91,1.97
252,E0,1.30,5.50,9.50,1.34,5.50,8.25,1.33,5.50,8.75,...,2.15,-1.25,1.87,2.03,1.88,2.05,1.91,2.19,1.86,2.03
253,E0,2.20,3.30,3.50,2.20,3.30,3.30,2.30,3.25,3.30,...,1.70,-0.25,1.91,1.99,1.93,2.00,1.96,2.02,1.90,1.97
254,E0,10.00,5.75,1.28,9.50,5.50,1.31,11.00,6.00,1.27,...,2.50,1.75,1.92,1.98,2.01,1.89,2.05,1.99,1.95,1.92
255,E0,2.05,3.30,3.80,2.05,3.20,3.80,2.10,3.25,3.70,...,1.63,-0.50,1.94,1.96,1.94,1.98,1.97,2.00,1.94,1.94

In [9]:
data.drop(removed_list, axis=1, inplace=True)
data

,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,AC,HY,AY,HR,AR,MaxH,MaxD,MaxA,Max>2.5,Max<2.5
0,13/08/2021,20:00,Brentford,Arsenal,2,0,H,1,0,H,...,5,0,0,0,0,4.62,3.72,2.10,2.26,1.83
1,14/08/2021,12:30,Man United,Leeds,5,1,H,1,0,H,...,4,1,2,0,0,1.59,4.65,6.35,1.71,2.38
2,14/08/2021,15:00,Burnley,Brighton,1,2,A,1,0,H,...,6,2,1,0,0,3.33,3.20,2.60,2.56,1.63
3,14/08/2021,15:00,Chelsea,Crystal Palace,3,0,H,2,0,H,...,2,0,0,0,0,1.30,6.30,15.00,1.84,2.12
4,14/08/2021,15:00,Everton,Southampton,3,1,H,0,1,A,...,8,2,0,0,0,2.04,3.66,4.25,2.14,1.85
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
251,26/02/2022,15:00,Crystal Palace,Burnley,1,1,D,1,0,H,...,4,0,2,0,0,2.02,3.60,4.34,2.41,1.70
252,26/02/2022,15:00,Man United,Watford,0,0,D,0,0,D,...,3,0,0,0,0,1.38,5.80,10.19,1.69,2.37
253,26/02/2022,15:30,Brighton,Aston Villa,0,2,A,0,1,A,...,2,4,5,0,0,2.35,3.42,3.52,2.26,1.78
254,26/02/2022,17:30,Everton,Man City,0,1,A,0,0,D,...,4,3,2,0,0,12.50,6.50,1.32,1.60,2.57
255,27/02/2022,14:00,West Ham,Wolves,1,0,H,0,0,D,...,5,1,0,0,0,2.20,3.35,4.28,2.41,1.72